import { useEffect, useState, useCallback } from 'react';
import { FileText, Trash2, RefreshCw, Download } from 'lucide-react';
import { adminApi } from '../services/adminApi';
import { type Report } from '../types';
import KPICard from '../components/KPICard';
import LoadingSpinner from '../components/LoadingSpinner';

export default function ReportManagement() {
  const [reports, setReports] = useState<Report[]>([]);
  const [total, setTotal]     = useState(0);
  const [summary, setSummary] = useState<{ reports_today: number; type_breakdown: { type: string; count: number }[] }>({ reports_today: 0, type_breakdown: [] });
  const [page, setPage]       = useState(1);
  const [loading, setLoading] = useState(true);
  const [msg, setMsg]         = useState('');
  const limit = 20;

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const r = await adminApi.getReports({ page, limit });
      setReports(r.data.reports);
      setTotal(r.data.total);
      setSummary(r.data.summary);
    } finally { setLoading(false); }
  }, [page]);

  useEffect(() => { load(); }, [load]);

  async function handleDelete(id: number) {
    if (!confirm('Delete this report? The file will also be removed from disk.')) return;
    await adminApi.deleteReport(id);
    setMsg('Report deleted'); load();
  }

  return (
    <div className="page-wrapper">
      <div className="page-header">
        <div>
          <h1 className="page-title">Report Management</h1>
          <p className="page-subtitle">{total} reports in system</p>
        </div>
        <button onClick={load} className="btn-secondary"><RefreshCw size={14} />Refresh</button>
      </div>

      {msg && <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-sm text-emerald-400">{msg}</div>}

      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        <KPICard title="Total Reports"  value={total}                  icon={FileText}  color="blue" />
        <KPICard title="Reports Today"  value={summary.reports_today}  icon={Download}  color="green" />
        <KPICard title="Report Types"   value={summary.type_breakdown.length} icon={FileText} color="purple" />
      </div>

      {/* Type breakdown */}
      {summary.type_breakdown.length > 0 && (
        <div className="glass-card p-5">
          <p className="text-sm font-semibold text-slate-300 mb-3">Report Type Breakdown</p>
          <div className="flex flex-wrap gap-2">
            {summary.type_breakdown.map(t => (
              <div key={t.type} className="px-3 py-1.5 rounded-lg bg-white/[0.05] border border-white/[0.08] text-xs">
                <span className="text-slate-400">{t.type || 'Unknown'}: </span>
                <span className="text-white font-semibold">{t.count}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="glass-card overflow-hidden">
        {loading ? <LoadingSpinner /> : (
          <div className="overflow-x-auto">
            <table className="admin-table">
              <thead>
                <tr><th>#</th><th>Type</th><th>Reconciliation</th><th>Generated By</th><th>Generated At</th><th></th></tr>
              </thead>
              <tbody>
                {reports.map(r => (
                  <tr key={r.id}>
                    <td className="font-mono text-slate-500">#{r.id}</td>
                    <td><span className="badge-blue">{r.report_type || 'PDF'}</span></td>
                    <td className="text-slate-400">Recon #{r.reconciliation_id}</td>
                    <td className="text-slate-400">User #{r.generated_by_id}</td>
                    <td className="text-slate-500 text-xs">{r.generated_at ? new Date(r.generated_at).toLocaleString() : '—'}</td>
                    <td>
                      <button className="btn-ghost text-red-400 hover:bg-red-500/10" onClick={() => handleDelete(r.id)}>
                        <Trash2 size={12} />
                      </button>
                    </td>
                  </tr>
                ))}
                {reports.length === 0 && <tr><td colSpan={6} className="text-center text-slate-500 py-12">No reports found</td></tr>}
              </tbody>
            </table>
          </div>
        )}
        {Math.ceil(total / limit) > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-white/[0.06]">
            <p className="text-xs text-slate-500">Page {page} of {Math.ceil(total / limit)}</p>
            <div className="flex gap-2">
              <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="btn-secondary px-3 py-1.5 text-xs disabled:opacity-40">Prev</button>
              <button onClick={() => setPage(p => p + 1)} disabled={page >= Math.ceil(total / limit)} className="btn-secondary px-3 py-1.5 text-xs disabled:opacity-40">Next</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
