import os
from datetime import datetime
from sqlalchemy.orm import Session
from fastapi import HTTPException
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from app.models.inventory import Report, Reconciliation, Discrepancy
from app.models.user import User


from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
from app.models.inventory import Report, Reconciliation, Discrepancy
from app.models.user import User

class ReportService:
    PRIMARY = HexColor("#0F172A")
    SECONDARY = HexColor("#64748B")
    ACCENT = HexColor("#E2E8F0")
    SURFACE = HexColor("#F8FAFC")
    WHITE = HexColor("#FFFFFF")
    BLACK = HexColor("#1E293B")

    @staticmethod
    def draw_footer_later(canvas, doc):
        canvas.saveState()
        canvas.setStrokeColor(HexColor("#CBD5E1"))
        canvas.setLineWidth(0.5)
        canvas.line(50, 50, 562, 50)
        
        canvas.setFont("Times-Roman", 8)
        canvas.setFillColor(ReportService.SECONDARY)
        canvas.drawString(50, 38, "Version 1.0 | Generated By AIMS | Classification: Internal Use")
        canvas.drawRightString(562, 38, f"Page {doc.page}")
        canvas.restoreState()

    @staticmethod
    def draw_footer_first(canvas, doc):
        canvas.saveState()
        canvas.setFont("Times-Roman", 8)
        canvas.setFillColor(ReportService.SECONDARY)
        canvas.drawString(50, 38, "Classification: Internal Use")
        canvas.restoreState()

    @staticmethod
    def generate_pdf_report(db: Session, recon_id: int, user: User) -> Report:
        recon = db.query(Reconciliation).filter(Reconciliation.id == recon_id).first()
        if not recon:
            raise HTTPException(status_code=404, detail="Reconciliation not found")

        discrepancies = (
            db.query(Discrepancy)
            .filter(Discrepancy.reconciliation_id == recon_id)
            .all()
        )

        os.makedirs("reports", exist_ok=True)
        timestamp_str = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
        file_path = f"reports/reconciliation_{recon_id}_{timestamp_str}.pdf"

        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=60,
        )

        styles = getSampleStyleSheet()
        
        # Define Times New Roman Typography Styles
        styles.add(ParagraphStyle(
            name="CoverTitle",
            fontName="Times-Bold",
            fontSize=20,
            leading=24,
            textColor=ReportService.PRIMARY,
            spaceAfter=12,
            alignment=TA_CENTER,
        ))
        styles.add(ParagraphStyle(
            name="CoverSubtitle",
            fontName="Times-Bold",
            fontSize=14,
            leading=18,
            textColor=ReportService.SECONDARY,
            spaceAfter=30,
            alignment=TA_CENTER,
        ))
        styles.add(ParagraphStyle(
            name="SectionHead9",
            fontName="Times-Bold",
            fontSize=12,
            leading=16,
            textColor=ReportService.PRIMARY,
            spaceBefore=14,
            spaceAfter=6,
        ))
        styles.add(ParagraphStyle(
            name="BodyTimes",
            fontName="Times-Roman",
            fontSize=9.5,
            leading=13,
            textColor=ReportService.BLACK,
            spaceAfter=6,
        ))
        styles.add(ParagraphStyle(
            name="BodyTimesBold",
            fontName="Times-Bold",
            fontSize=9.5,
            leading=13,
            textColor=ReportService.BLACK,
            spaceAfter=6,
        ))

        elements = []

        # ─── COVER PAGE ───
        elements.append(Spacer(1, 80))
        elements.append(Paragraph("AI-Powered Multi-Agent Inventory Reconciliation &<br/>Enterprise Asset Governance Platform", styles["CoverTitle"]))
        elements.append(Paragraph("Executive Governance Assessment Report", styles["CoverSubtitle"]))
        elements.append(Spacer(1, 100))

        # Metadata Table
        report_id_sim = f"REP-{recon_id}-{timestamp_str[:8]}"
        meta_data = [
            [Paragraph("<b>Report ID:</b>", styles["BodyTimesBold"]), Paragraph(report_id_sim, styles["BodyTimes"])],
            [Paragraph("<b>Generation Date:</b>", styles["BodyTimesBold"]), Paragraph(datetime.utcnow().strftime('%B %d, %Y'), styles["BodyTimes"])],
            [Paragraph("<b>Reconciliation ID:</b>", styles["BodyTimesBold"]), Paragraph(f"#{recon_id}", styles["BodyTimes"])],
            [Paragraph("<b>Classification:</b>", styles["BodyTimesBold"]), Paragraph("Internal Use Only", styles["BodyTimes"])],
        ]
        meta_table = Table(meta_data, colWidths=[2.5 * inch, 3.5 * inch])
        meta_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("GRID", (0, 0), (-1, -1), 0.5, ReportService.ACCENT),
            ("PADDING", (0, 0), (-1, -1), 8),
            ("BACKGROUND", (0, 0), (-1, -1), ReportService.SURFACE),
        ]))
        elements.append(meta_table)
        elements.append(PageBreak())

        # ─── SECTION 1: Executive Summary ───
        elements.append(Paragraph("1. Executive Summary", styles["SectionHead9"]))
        exec_summary_text = recon.executive_summary or "AI Insights temporarily unavailable. The core discrepancy mapping algorithm completed successfully."
        elements.append(Paragraph(exec_summary_text, styles["BodyTimes"]))
        elements.append(Spacer(1, 10))

        # ─── SECTION 2: Governance Overview ───
        elements.append(Paragraph("2. Governance Overview", styles["SectionHead9"]))
        gov_score = max(0, 100 - (recon.missing_assets_count + recon.untracked_assets_count + recon.config_mismatch_count + recon.naming_mismatch_count))
        overview_text = (
            f"Governance review indicates a score posture of {gov_score}/100. This is calculated from asset catalog sync "
            f"mismatches, including untracked resources and config drifts. Total deviations are logged in section 3."
        )
        elements.append(Paragraph(overview_text, styles["BodyTimes"]))
        elements.append(Spacer(1, 10))

        # ─── SECTION 3: Reconciliation Findings ───
        elements.append(Paragraph("3. Reconciliation Findings", styles["SectionHead9"]))
        kpi_data = [
            ["Metric Category", "Baseline Registry", "Discovered Live", "Deviations Logged"],
            ["Registered Inventory (CSV)", str(recon.total_csv_assets), "—", "—"],
            ["Infrastructure Snap (JSON)", "—", str(recon.total_json_assets), "—"],
            ["Missing Assets Registry", "—", "—", str(recon.missing_assets_count)],
            ["Untracked Active Servers", "—", "—", str(recon.untracked_assets_count)],
            ["Configuration Parameters Drifts", "—", "—", str(recon.config_mismatch_count)],
            ["Naming Identifier Drifts", "—", "—", str(recon.naming_mismatch_count)],
        ]
        kpi_table = Table(kpi_data, colWidths=[2.5 * inch, 1.25 * inch, 1.25 * inch, 1.25 * inch])
        kpi_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), ReportService.PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), ReportService.WHITE),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Times-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, ReportService.ACCENT),
            ("BACKGROUND", (0, 1), (-1, -1), ReportService.SURFACE),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [ReportService.WHITE, ReportService.SURFACE]),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(kpi_table)
        elements.append(Spacer(1, 10))

        # ─── SECTION 4: Historical Comparison ───
        elements.append(Paragraph("4. Historical Comparison", styles["SectionHead9"]))
        hist_text = (
            f"Historical database analysis logs comparison registers. Run #{recon_id} holds match accuracy index "
            f"derived directly from the inventory upload registers."
        )
        elements.append(Paragraph(hist_text, styles["BodyTimes"]))
        elements.append(Spacer(1, 10))

        # ─── SECTION 5: Asset Health Analysis ───
        elements.append(Paragraph("5. Asset Health Analysis", styles["SectionHead9"]))
        health_text = (
            f"Out of {recon.total_csv_assets} registered items, {recon.total_json_assets} were validated. "
            f"Drift profile shows configuration drift is active on {recon.config_mismatch_count} instances."
        )
        elements.append(Paragraph(health_text, styles["BodyTimes"]))
        elements.append(Spacer(1, 10))

        # ─── SECTION 6: Critical Findings ───
        elements.append(Paragraph("6. Critical Findings", styles["SectionHead9"]))
        disc_data = [["Asset ID", "Type", "Root Cause", "Impact", "Effort", "Reduction"]]
        for d in discrepancies[:8]:
            disc_data.append([
                d.csv_asset_id or d.json_asset_id or "—",
                d.discrepancy_type.value.replace("_", " "),
                (d.root_cause or "Sync fail")[:20],
                (d.business_impact or "Compliance vulnerability")[:20],
                d.estimated_effort or "1 Hour",
                d.expected_risk_reduction or "15%"
            ])
        if len(discrepancies) == 0:
            disc_data.append(["—", "—", "No discrepancies logged", "—", "—", "—"])
            
        disc_table = Table(disc_data, colWidths=[0.8 * inch, 1.1 * inch, 1.3 * inch, 1.3 * inch, 0.7 * inch, 1 * inch])
        disc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), ReportService.PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), ReportService.WHITE),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("FONTNAME", (0, 0), (-1, 0), "Times-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, ReportService.ACCENT),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [ReportService.WHITE, ReportService.SURFACE]),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(disc_table)
        elements.append(Spacer(1, 10))

        # ─── SECTION 7: AI Recommendations ───
        elements.append(Paragraph("7. AI Recommendations", styles["SectionHead9"]))
        ai_analysis_text = recon.ai_analysis or "AI Insights temporarily unavailable. Please run standard compliance remediations."
        elements.append(Paragraph(ai_analysis_text, styles["BodyTimes"]))
        elements.append(Spacer(1, 10))

        # ─── SECTION 8: Governance Forecast ───
        elements.append(Paragraph("8. Governance Forecast", styles["SectionHead9"]))
        forecast_text = (
            f"Forecast engine projections: resolving config drifts and naming mismatches "
            f"will elevate overall governance score posture to 100/100, mitigating security exposure threats."
        )
        elements.append(Paragraph(forecast_text, styles["BodyTimes"]))
        elements.append(Spacer(1, 10))

        # ─── SECTION 9: Audit Readiness ───
        elements.append(Paragraph("9. Audit Readiness", styles["SectionHead9"]))
        readiness_score = int(max(0, 100 - (recon.missing_assets_count * 3 + recon.untracked_assets_count * 2 + recon.config_mismatch_count * 1.5 + recon.naming_mismatch_count * 0.5)))
        readiness_text = (
            f"Executive Audit Readiness Stance is calculated at: {readiness_score}%. "
            f"Calculation weight profile: Missing registry items (-3pts), Untracked active servers (-2pts), "
            f"Configuration Drifts (-1.5pts), and Naming conflicts (-0.5pts)."
        )
        elements.append(Paragraph(readiness_text, styles["BodyTimes"]))

        doc.build(elements, onFirstPage=ReportService.draw_footer_first, onLaterPages=ReportService.draw_footer_later)

        report = Report(
            reconciliation_id=recon_id,
            generated_by_id=user.id,
            report_type="PDF",
            file_path=file_path,
            executive_summary=recon.executive_summary,
        )
        db.add(report)
        db.commit()
        db.refresh(report)

        # Enforce history limit: Keep latest 5 reports only
        total_reports = db.query(Report).count()
        if total_reports > 5:
            oldest_reports = (
                db.query(Report)
                .order_by(Report.generated_at.asc())
                .limit(total_reports - 5)
                .all()
            )
            for old in oldest_reports:
                if old.file_path and os.path.exists(old.file_path):
                    try:
                        os.remove(old.file_path)
                    except Exception:
                        pass
                db.delete(old)
            db.commit()

        return report
